Form/Type/RichHtmlType.php
<?php
/**
 * Created by PhpStorm.
 * User: carles
 * Date: 29/4/17
 * Time: 11:53
 */

namespace CarlesPibernat\AdminGeneratorBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;


class RichHtmlType extends AbstractType
{
    public function getParent()
    {
        return TextType::class;
    }
}

Resources/views/form/fields.html.twig
{% use "form_div_layout.html.twig" %}

{% block rich_html_widget %}
    {% spaceless %}
        <div id="quill-editor">
            {{ form.vars.value | raw }}
        </div>

        <input id="{{ form.vars.full_name }}" type="hidden" name="{{ form.vars.full_name }}">

        <script>
            var quill = new Quill('#quill-editor', {
                theme: 'snow'
            });

            var form = document.getElementsByName("{{ form.parent.vars.full_name }}")[0];

            form.onsubmit = function() {
                var input = document.getElementsByName("{{ form.vars.full_name }}")[0];
                input.value = quill.container.firstChild.innerHTML;
            }
        </script>
    {% endspaceless %}
{% endblock %}

{% block checkbox_widget %}
    {% spaceless %}
        {% if form.vars.label %}
            <label for="{{ form.vars.id }}" {% if form.vars.required %}class="required"{% endif %}>{{ form.vars.label }}</label>
        {% endif %}
        <input id="{{ form.vars.id }}" {{ block('widget_attributes') }} type="checkbox" {% if value is not empty %}value="{{ value }}" {% endif %}{% if form.vars.checked %}checked{% endif %}>

        <script>
            var elem = document.getElementById('{{ form.vars.id }}');
            var init = new Switchery(elem, { size: 'small' });
        </script>
    {% endspaceless %}
{% endblock %}